[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "article-checklist-manager"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["typer>=0.9"]

[project.scripts]
acm = "acm.cli:app"
